services:
  # --- Backend Servisi ---
  api:
    build: .
    container_name: socialphoto_backend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env  # TÜM DEĞİŞKENLERİ BURADAN ÇEKER
    environment:
      - PORT=3000
      - NODE_ENV=development
      # DATABASE_URL'i buraya da yazıyoruz ki Docker içindeki 'db' ismini görsün
      - DATABASE_URL=postgresql://postgres:12345@db:5432/socialphoto_db?schema=public
    volumes:
      - ./src:/app/src
      - /app/node_modules
    command: npm run dev
    depends_on:
      - db

  # --- Veritabanı Servisi ---
  db:
    image: postgres:15-alpine
    container_name: socialphoto_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=socialphoto_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: